# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
array = np.arange(10, 50)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [4]:
np.shape(array)

(40,)

5. Print the type of the previous array in question 3

In [5]:
array.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [6]:
print(np.__version__)
np.show_config()

1.18.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


7. Print the dimension of the array in question 3


In [7]:
array.ndim

1

8. Create a boolean array with all the True values

In [8]:
boolArray = np.array([True, True, True])

9. Create a two dimensional array




In [9]:
array2D = np.array([[1,2,3],[4,5,6]])

10. Create a three dimensional array



In [10]:
array3D = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
print(array)
np.flip(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
nullVector = np.zeros(10)
nullVector[4] = 1
print(nullVector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [13]:
np.eye(3)        # np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1, 2, 3, 4, 5], dtype=np.float16)
print(arr.dtype)

float16


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1>arr2

array([[ True, False,  True],
       [False,  True, False]])

17. Extract all odd numbers from arr with values(0-9)

In [17]:
array = np.arange(0, 10)
array[array%2 != 0]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [18]:
array[array%2 != 0] = 1
array

array([0, 1, 2, 1, 4, 1, 6, 1, 8, 1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [20]:
np.array([[1,1,1],[1,0,1],[1,1,1]])

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6], 
                  [7, 8, 9]])
arr2d[1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0][0] = 64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
arr2D = np.arange(0,9).reshape(3,3)
arr2D[0]

array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
arr2D = np.arange(0,9).reshape(3,3)
arr2D[1][1]

4

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
arr2D = np.arange(0,9).reshape(3,3)
print(arr2D)
arr2D[:2, 2:]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2],
       [5]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
array = np.random.random((10,10))
print(array)
print(np.max(array))
print(np.min(array))

[[0.85469783 0.38090636 0.68914581 0.85560183 0.34351644 0.68558362
  0.85718059 0.17801683 0.45999397 0.85329937]
 [0.64315456 0.9593972  0.85878195 0.22151723 0.28350839 0.90859822
  0.59362951 0.51230004 0.46156058 0.75465194]
 [0.58893551 0.90542144 0.81506354 0.3526836  0.07735905 0.93281152
  0.49424227 0.86623847 0.03979492 0.214781  ]
 [0.44153805 0.05481374 0.68280374 0.02750003 0.97576173 0.72869902
  0.29612495 0.47266866 0.71209224 0.18487805]
 [0.30251983 0.48639351 0.44685386 0.48651558 0.72970778 0.50006257
  0.23007493 0.24521142 0.22766077 0.02364111]
 [0.08436663 0.4584586  0.83888398 0.82942785 0.70896191 0.92322434
  0.31851169 0.05989646 0.20906561 0.66499208]
 [0.75109584 0.15366359 0.39144467 0.50626    0.36567329 0.54506699
  0.43984284 0.23291616 0.83086633 0.90651163]
 [0.12039736 0.04188699 0.86596518 0.67592727 0.12328566 0.85483939
  0.47753752 0.88042336 0.75254649 0.26640727]
 [0.51926897 0.72383366 0.3412295  0.69667132 0.76766889 0.64685196
  0.86628889

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(np.in1d(a,b))

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names=="Will"]

array([[-1.47586378e-01, -7.51944228e-01,  2.94486303e-02,
         8.56231330e-01],
       [ 5.45948917e-04,  1.37014311e-01, -2.65191925e-01,
         1.83124508e+00]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
condition = ~((names == "Will") | (names == "Joe"))
data[condition]

array([[-0.72494238,  0.63645641, -0.05144788,  0.69995959],
       [-0.60131239,  0.16158499,  0.32165751, -1.60490535]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [31]:
np.arange(1,16).reshape(5,3).astype("float16")

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]], dtype=float16)

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [32]:
np.arange(1,17).reshape(2, 2, 4).astype("float16")

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]], dtype=float16)

33. Swap axes of the array you created in Question 32

In [33]:
np.arange(1,17).reshape(2, 2, 4).astype("float16").swapaxes(0,2)

array([[[ 1.,  9.],
        [ 5., 13.]],

       [[ 2., 10.],
        [ 6., 14.]],

       [[ 3., 11.],
        [ 7., 15.]],

       [[ 4., 12.],
        [ 8., 16.]]], dtype=float16)

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [34]:
array = np.sqrt(np.arange(1, 11))
array[array < 0.5] = 0
array

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [35]:
a = np.random.random(12)
b = np.random.random(12)
np.maximum(a,b)

array([0.84208891, 0.89365215, 0.79832596, 0.64126487, 0.81435882,
       0.53979431, 0.90383874, 0.60398296, 0.91588693, 0.80922145,
       0.84595634, 0.57747811])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
a = np.unique(names)
a.sort()
a

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [37]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
b = b[~np.in1d(b,a)]
b

array([6, 7, 8, 9])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [38]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray = np.delete(sampleArray, 2, axis=1)
np.insert(sampleArray, 2, newColumn, axis=1)

array([[34, 43, 10],
       [82, 22, 10],
       [53, 94, 10]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [39]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [40]:
np.cumsum(np.random.random(20))

array([0.39468382, 1.23727   , 1.2934489 , 1.53577781, 2.5071426 ,
       2.71877274, 3.37020986, 3.85738063, 4.28224799, 4.6369467 ,
       5.53405978, 5.84206055, 6.74220646, 7.23555646, 7.66944318,
       7.70691789, 8.19398282, 8.24939201, 8.90196063, 8.96127632])